### ISSUE TITLE
conflicts  with higher versions of  guzzlehttp/guzzle[

### ISSUE THREAD

**Issue by khaled2315** [mrkindy/EgyaptianEInvoice#4]
![0000](https://user-images.githubusercontent.com/24880840/206416515-84b66155-c73b-4419-abdd-c735b0a4a280.PNG)

**Comment by itsnasser** [comment]
I have faced this problem so I fork the package and updated the guzzle version to 7 , to work with new versions of laravel 
you can try this fork until the pull request accepted
```composer require itsnasser/egyptian-e-invoice ```

**Comment by mrkindy** [comment]
> I have faced this problem so I fork the package and updated the guzzle version to 7 , to work with new versions of laravel you can try this fork until the pull request accepted `composer require itsnasser/egyptian-e-invoice `

we have merged your request thank you for your contribution
